OnlineWeb/CartApp/urls.py
from django.urls import path
from . import views

app_name = 'CartApp'

urlpatterns = [

    path('cart', views.cartdetail, name='cartdetail'),
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),    
    path('delete/<int:product_id>/', views.cart_delete, name = 'cart_delete'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('address',views.delivery, name='delivery')
]

OnlineWeb/OnlineApp/urls.py
from django.urls import path
from . import views

app_name = 'OnlineApp'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.productdetail, name='productdetail'),
    path('exclusive', views.exclusive, name="exclusive")
]

OnlineWeb/OnlineWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('OnlineApp.urls')),
    # path('shop/', include('OnlineApp.urls')),
    path('search/', include('SearchApp.urls')),
    path('cart/',include('CartApp.urls')),
    path('login', include('credentials.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

OnlineWeb/SearchApp/urls.py
from django.urls import path
from .import views

app_name = 'SearchApp'

urlpatterns =[
    path('search', views.searchresults, name='sreachresults')
]

OnlineWeb/credentials/urls.py
from django.urls import path
from . import views

app_name = 'loginapp'

urlpatterns = [
    path('',views.login, name="login"),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
]

OnlineWeb/templates/address.html
{% extends 'base.html' %}

{% block content %}
    <div class="container"><br>
    <h2><u>Delivery Information</u></h2><br>
    <form>
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" placeholder="Enter your name" required>
        </div>
        <div class="form-group">
            <label for="address">Address:</label>
            <textarea class="form-control" id="address" rows="3" placeholder="Enter your address" required></textarea>
        </div>
        <div class="form-group">
            <label for="Mobile">Mobile Number :</label>
            <input type="text" class="form-control" id="name" placeholder="Enter your Mob Number" required>
        </div>
        <div class="form-group">
            <label for="Landmark">Landmark :</label>
            <input type="text" class="form-control" id="name" placeholder="Enter your Landmark" required>
        </div>
        <a href="{% url 'OnlineApp:allProdCat' %}" class="btn-head">Place Your Order</a>
</div>
<br><br>
{% endblock %}

OnlineWeb/templates/cart.html
{% extends 'base.html' %}
{% block content %}
{% if not cart_items %}

<div>
    <div class="text-center">
        <br>
        <h1 class="text-center cart_title">
            Your Shopping Cart is Empty
        </h1>
        <br>
        <p class="text-center">Please Click<a href="{% url 'OnlineApp:allProdCat' %}"> HERE</a> to Explore</p>
    </div>
</div>

{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center cart_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="cart-container">
    <!-- Left side content -->
    <div class="cart-left">
        <table class="cart_custom_table">
            <thead class="cart_custom_th">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img style ="width:100px;height:100px" class="my_image" src="{{cart_item.product.image.url}}" alt="{{cart_item.product.name}}" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU : {{cart_item.product.id}}
                    <br>
                    Price : $ {{cart_item.product.price}}
                    <br>
                    Quantity : {{cart_item.quantity}} Nos
                    <br>
                    $ {{cart_item.sub_total}}
                
                {% if cart_item.quantity < cart_item.product.stock %}
                
                    <a href="{% url 'CartApp:add_cart' cart_item.product.id %}" class="custom_a">
                        &nbsp;&nbsp;<i class="fa-solid fa-plus custom_icon" ></i></a>
                        &nbsp; &nbsp;<a href="{% url 'CartApp:cart_delete' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon" ></i></a>
                        &nbsp;&nbsp;<a href="{% url 'CartApp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash"></i></a>                    
                </td>
                {% else %}
                <td>
                        &nbsp;<a href="{% url 'CartApp:cart_delete' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon" ></i></a>
                        &nbsp;<a href="{% url 'CartApp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash"></i></a>                    
                </td>
                {% endif %}
            </tr>
            {% endfor %}   
        </table>
    </div>


<div class="cart-right">
    <!-- Order form -->
    <div class="order-form">
        <h2>Place Your Order</h2>
        <table class="cart_custom_table">
            <thead class="cart_custom_th">
                <tr>
                    <th>
                        CheckOut
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please reiew Your Shopping cart Items before Proceeding with the order payment.
                    </td>
                </tr>
                <tr>
                    <td>
                        Your Total is <strong> ${{ total }}</strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'OnlineApp:allProdCat' %}" class="btn btn-secondary btn_block my_custom_btn">Continue Shopping</a>
            <a href="{% url 'CartApp:delivery' %}" class="btn btn-secondary">Buy Now</a>
        </div>
    </div>
    </div>
</div>
{% endif %}

    {% endblock %}

OnlineWeb/templates/category.html
{% extends 'base.html' %}
{% load static %}

<!--META DESCCRIPTION SECTION-->
{% block metadescription %}
    {% if category %}
        {{ category.description| truncatewords:155 }}
    {% else %}
        Shop - Onlineshopping Site - You can buy different items from here!!!
    {% endif %}
{% endblock %}

<!--TITLE SECTION-->
{% block title %}
    {% if category %}
        {{ category.name }}  - Onlineshop
    {% else %}
        Shopping items
    {% endif %}
{% endblock %}


<!--CATEGORY & PRODUCT SECTION-->
{% block content %}
{% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto ">
            <p><a href="{% url 'OnlineApp:allProdCat' %}">OUR CATEGORIES COLLECTION</a></p>
        </div>
        
    </div>
</div>
{% endif %}

<div class="o">
    {% if category %}
        <img class="" src="{{ category.image.url }}" alt="{{ category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{ category.name }}</h1>
    <p class="text-justify">{{ category.descriptipn }}</p>
</div>
    {% else %}
    <div class="my_row">
        <div class="col2">
            <h1 class="text-center">Give you workout <br>A new style !!!</h1>
            <p class="text-center">Sucess is not always about greatness, Its all about consistancy. Consistent <br>hard work gain sucess.Greatness will come</p>
        <div class="h">
            <a href="{% url 'OnlineApp:exclusive' %}" class="btn-head">Explore Now &#8594;</a>
        </div>
            
        </div>
        <div class="col2">
            <img src="{% static 'img\banner.png' %}">
        </div>
    </div>
    <!-- <div>
        <img class="my_image my_image_padding"src="{% static 'img/banner.png' %}" alt="Our products">
    </div> -->
    <div class="cat_sec">
        <div class="cut_div">
            <h1 class="text-center my_title-1">OUR PRODUCTS COLLECTIONS</h1>
            <!-- <P class="text-center">Explore our curated collection of football studs, designed 
                for both amateur and professional players. From precision-engineered studs for 
                firm ground to versatile options for turf and indoor courts, we’ve got you covered. 
                Elevate your game with top brands like Adidas Originals, 
                Puma, and Nike. Score big on style and performance!</P> -->
        </div>
        {% endif %}
    
        <!-- <div class="container">
            <div class="row mx_auto">
                {% for product in products.object_list %}
                <div class="my_bottom_margin col-md-2 col-sm-6 col-md-4 xol-lg-4">
                    <div class="card text-center " style="min-width: 18rem;">
                        <a href="{{ product.get_url }}"><img class= "card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
                        <div class="crad-body">
                            <h4>{{ product.name }}</h4>
                            <p> $ {{ product.price }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %} -->
            </div>
            <div class="mx-auto">
                {% if products.paginator.num_pages > 1 %}
    
                 
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            </div>
            {% endif %} <hr>
    
        </div>
    </div>

    <div class="card-container">
        {% for product in products.object_list %}
            <div class="card-1" > <!---product card settings--->
                <a href="{{ product.get_url }}"><img class= "card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}" style="align-items: center;margin-top: 20px;border-radius: 20px;"></a>
                <div class="card-content">
                    <h2 class="card-title">{{ product.name }}</h2>
                </div>
                <a class="product-button" href="{{ product.get_url }}">View More</a>
                <!-- <button onclick="location.href= class="product-button">View More</button> -->
            </div>
        {% endfor %}
    </div>
    


{% endblock %}

OnlineWeb/templates/exclusive.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="ex_offer">
    <div class="ex_smallcontainer">
        <div class="row">
            <div class="col2 ex">
                <img src="{% static 'img/exclusive/exclusive.png' %}" class="offerimg">
            </div>
            <div class="col2 ex">
                <p class="offertitle">EXCLUSIVELY AVAILABLE !!!</p>
                <h1>Mi Smart Band 4</h1>
                <small>Mi Smart Band 4 0.94-inch AMOLED Color Display, 20 Days Battery, color AMOLED full touch display</small>
                <a href="{% url 'OnlineApp:allProdCat' %}" class="btn-head" style="justify-content: center;">Buy Now &#8594;</a>
            </div>
            <!-- <div>
                <a href="" class="btn-head" >Buy Now &#8594;</a>
            </div> -->
            
        </div>
    </div>
</div>
{% endblock %}

OnlineWeb/templates/login.html
{% load static %}
<style>

/* *,
*:before,
*:after {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
    background: radial-gradient(#fff,#f80303);
}

input,
button {
    border: none;
    outline: none;
    background: none;
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
}

.cont {
    border-radius: 20px;
    overflow: hidden;
    position: relative;
    width: 900px;
    height: 550px;
    margin: 0 auto 100px;
    background: #fff;
    box-shadow: -10px -10px 15px rgba(255, 255, 255, 0.3), 10px 10px 15px rgba(70, 70, 70, 0.15), inset -10px -10px 15px rgba(255, 255, 255, 0.3), inset 10px 10px 15px rgba(70, 70, 70, 0.15);
}

.form {
    position: relative;
    padding: 50px 30px 0;
}

button {
    display: block;
    margin: 0 auto;
    width: 260px;
    height: 36px;
    border-radius: 30px;
    color: #fff;
    font-size: 15px;
    cursor: pointer;
}

h2 {
    width: 100%;
    font-size: 26px;
    text-align: center;
}

label {
    display: block;
    width: 260px;
    margin: 25px auto 0;
    text-align: center;
}

label span {
    font-size: 12px;
    color: #cfcfcf;
    text-transform: uppercase;
}

input {
    display: block;
    width: 100%;
    margin-top: 5px;
    padding-bottom: 5px;
    font-size: 10px;
    border-bottom: 1px solid rgba(0, 0, 0, 0.4);
    text-align: center;
}

.forgot-pass {
    margin-top: 15px;
    text-align: center;
    font-size: 12px;
    color: #cfcfcf;

}

.forgot-pass_a{
    text-decoration: none;
}

.submit {
    margin-top: 40px;
    margin-bottom: 20px;
    background: #d4af7a;
    text-transform: uppercase;
} */
</style>


    


<link rel="stylesheet" href="{% static 'css/login.css' %}">

<!-- LOGIN SECTION -->

    <form action="" method="POST">
        {% csrf_token %}
    
    <br>
    <div class="cont">
        <div class="form sign-in">
            <h2>Welcome</h2>
            <label>
                <span>UserName</span>
                <input type="text" name="username" />
            </label>
            <label>
                <span>Password</span>
                <input type="password"name="password"  />
            </label>
            <!-- <input type="text" placeholder="Username" name="username" />
            <input type="password" placeholder="Password" name="password" /> -->
            <a href="#" class="forgot-pass_a"><p class="forgot-pass">Forgot password?</p></a>
            <a href="{% url 'loginapp:register' %}" class="create_a"><p class="Create">New to RedStore ! Welcome on Board &#129309 </p></a>
            <button type="submit" class="submit">Sign In</button>
                <center>{% for msg in messages %}
                    <p style="color: red;">{{msg}}</p>
                    {%endfor%}</center>
         </div>
         
       
        </form>

OnlineWeb/templates/nav.html
{% load static %}
<!-- <style>
    .RitSec{position: fixed;
    width: 100%;
    animation-name: fadeInDown;
    animation-duration: .8s;
    animation-fill-mode: both;
    z-index: 9000;
    top: 0px;
    background: #00aa95;
    box-shadow: 0px 0px 25px rgba(0,0,0,.1);
    }
</style> -->
<nav>
    <!-- <div class="RitSec">
        <div class="QckActn">
            <div class="ItM">
                <button type="button" aria-label="language" >International (English)</button>
            </div>
            <div class="ItM">
                <a href="index.php" title="login" aria-label="login">Login</a>
            </div>
        </div>
        <div class="MenuIcon">
            <button type="button" aria-label="MenuButton" class="btn" data-bs-toggle="modal"
                data-bs-target="#HeaderPOP">
                <div class="IconWrp">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
        </div> -->
<div class="navbar navbar-expand-lg bg-body-tertiary">
  
    <div class="container-fluid">
        <a href="{% url 'OnlineApp:allProdCat' %}"><img src="{% static 'img\logo.png' %}" alt="logoimage" width="125px"></a>
      <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-5 mb-lg-2">
          <li class="navitem-">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          
          <li class="nav-item dropdown  {% if 'OnlineApp in request.path' %} active {% endif %}" >
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Shop
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'OnlineApp:allProdCat' %}">All Products</a></li>
              <li><a class="dropdown-item" href="{%url 'CartApp:cartdetail' %}">Your Cart</a></li>
                {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                {% endfor %}

            </ul>
          </li>
          {% if item_count %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CartApp:cartdetail' %}"><i class="fa-solid fa-cart-shopping"></i>( {{item_count}} )</a>
          </li>
          {% endif %}
          <!-- {% if user.is_authenticated %}
          <img src="{ user.userprofile.image_url }" alt="">
          <li class="nav-link">{{ user.username }}</li>
          
          <li><a href="credentials/logout" class="nav-link">logout</a></li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loginapp:login' %}">LogIn</a>
          </li>
          {% endif %} -->
          {% if user.is_authenticated %}
    {% if user.userprofile.image_url %}
        <img class="user_image" src="{{ user.userprofile.image_url }}" alt="" >
    {% else %}
        <!-- If user image is not available, use a default image -->
        <img class= "nav-link" style="width: 40px;height: 40px;" src="{% static 'img/userimage/user.png' %}" alt="">
    {% endif %}
    <li class="nav-link">{{ user.username }}</li>
    <li><a href="{% url 'loginapp:logout' %}" class="nav-link">Logout</a></li>
{% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'loginapp:login' %}">LogIn</a>
    </li>
{% endif %}
        </ul>
        <form class="d-flex" role="search" action="{% url 'SearchApp:sreachresults' %}" method="GET">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><i class="fa-brands fa-searchengin"></i></button>
        </form>
      </div>
    </div>
</div>
<!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#0099ff" fill-opacity="1" d="M0,224L14.1,224C28.2,224,56,224,85,197.3C112.9,171,141,117,169,80C197.6,43,226,21,254,21.3C282.4,21,311,43,339,80C367.1,117,395,171,424,213.3C451.8,256,480,288,508,256C536.5,224,565,128,593,101.3C621.2,75,649,117,678,133.3C705.9,149,734,139,762,117.3C790.6,96,819,64,847,64C875.3,64,904,96,932,96C960,96,988,64,1016,96C1044.7,128,1073,224,1101,256C1129.4,288,1158,256,1186,229.3C1214.1,203,1242,181,1271,186.7C1298.8,192,1327,224,1355,240C1383.5,256,1412,256,1426,256L1440,256L1440,0L1425.9,0C1411.8,0,1384,0,1355,0C1327.1,0,1299,0,1271,0C1242.4,0,1214,0,1186,0C1157.6,0,1129,0,1101,0C1072.9,0,1045,0,1016,0C988.2,0,960,0,932,0C903.5,0,875,0,847,0C818.8,0,791,0,762,0C734.1,0,706,0,678,0C649.4,0,621,0,593,0C564.7,0,536,0,508,0C480,0,452,0,424,0C395.3,0,367,0,339,0C310.6,0,282,0,254,0C225.9,0,198,0,169,0C141.2,0,113,0,85,0C56.5,0,28,0,14,0L0,0Z"></path></svg> -->
</div>

OnlineWeb/templates/originalcart.html
{% extends 'base.html' %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center cart_title">
            Your Shopping Cart is Empty
        </h1>
        <br>
        <p class="text-center">Please Click<a href="{% url 'OnlineApp:allProdCat' %}"> HERE</a> to Explore</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center cart_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="cart_custom_table">
            <thead class="cart_custom_th">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img style ="width:100px;height:100px" class="my_image" src="{{cart_item.product.image.url}}" alt="{{cart_item.product.name}}" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU : {{cart_item.product.id}}
                    <br>
                    Price : $ {{cart_item.product.price}}
                    <br>
                    Quantity : {{cart_item.quantity}} x {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'CartApp:add_cart' cart_item.product.id %}" class="custom_a">
                        <i class="fa-solid fa-plus custom_icon" ></i></a>
                        &nbsp;<a href="{% url 'CartApp:cart_delete' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon" ></i></a>
                        &nbsp;<a href="{% url 'CartApp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash"></i></a>                    
                </td>
                {% else %}
                <td>
                        &nbsp;<a href="{% url 'CartApp:cart_delete' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon" ></i></a>
                        &nbsp;<a href="{% url 'CartApp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash"></i></a>                    
                </td>
                {% endif %}
            </tr>
            {% endfor %}   
        </table>
    </div>
</div>
</tbody>
<div class="row mx-auto">
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="cart_custom_table">
        <thead class="cart_custom_th">
            <tr>
                <th>
                    CheckOut
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Please reiew Your Shopping cart Items before Proceeding with the order payment.
                </td>
            </tr>
            <tr>
                <td>
                    Your Total is <strong> ${{ total }}</strong>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'OnlineApp:allProdCat' %}" class="btn btn-secondary btn_block my_custom_btn">Continue Shopping</a>
        <a href="" class="btn btn-secondary">Buy Now</a>
    </div>
</div>
</div>
{% endif %}
{% endblock %}

OnlineWeb/templates/productdeatil.html
{% extends 'base.html' %}
{% load static %}

<!--META DESCCRIPTION SECTION-->
{% block metadescription %}
    {% if product %}
        {{product.description| truncatewords:155 }}
    {% else %}
        Shop - Onlineshopping Site - You can buy different items from here!!!
    {% endif %}
{% endblock %}

<!--TITLE SECTION-->
{% block title %}
    {% if product %}
    {{product.name}}  - Onlineshop
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class mx_auto">
    <div >
        <p><a href="{% url 'OnlineApp:allProdCat' %}" class="options_details">HOME</a>  | <a href="{{product.category.get_url}}" class="options_details">{{ product.category }}</a>| <a href=""></a>{{ product.name }}</p>
    </div>
</div>
<div class="prod_container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width: 18rem;">
            <img style="width: 400px;height: 400px;" class="card-img-top my_img-1" src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>
    
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p > $ {{product.price}}</p>
            <p class="my_title">PRODUCT DESCRIPTION</p>
            <p class="text-justify">{{product.description}}</p>
            {% if product.stock == 0 %}
                <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
            {% else %}
                <a class="btn btn-secondary prod_btn" href="{% url 'CartApp:add_cart' product.id %}">ADD TO CART</a>
            {% endif %}
        </div>
        </div>

    
</div>
</div>
</div>
{% endblock %}

OnlineWeb/templates/search.html
{% extends 'base.html' %}
{% load static %}

<!--META DESCCRIPTION SECTION-->
{% block metadescription %}
    We have verity of Products and Get the Quality Items
{% endblock %}

<!--TITLE SECTION-->
{% block title %}
    Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for : <b>"{{query}}"</b>
    </p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
            <div class="card text-center " style="min-width: 18rem;">
                <a href="{{ product.get_url }}"><img class= "card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
                <div class="crad-body">
                    <h4>{{ product.name }}</h4>
                    <p> {{ product.price }}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">Zero results found !!!!</p>
            <p class="text-center my_search_text">Click <a href="{% url 'OnlineApp:allProdCat' %}">Here</a> for back to product section .</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

OnlineWeb/templates/video.html
{% load static %}


<style>
#tm-video {
    position: fixed;
    right: 0;
    bottom: 0;    
    z-index: -1000;
}

.tm-video-wrapper { 
    position: relative; 
}

#tm-video-control-button {
    cursor: pointer;
    position: fixed;
    bottom: 30px;
    right: 30px;
    z-index: 1000;
    background-color: rgba(0,0,0,0.5);
    color: white;    
    padding: 10px;
}
</style>


<div class="tm-video-wrapper">
    <i id="tm-video-control-button" class="fas fa-pause"></i>
    <video autoplay muted loop id="tm-video">
        <source src="{% static 'video/wave-cafe-video-bg.mp4' %}" type="video/mp4">
    </video>
</div>